export const bgObjs = [
  {
    id: 0,
    width: '40',
    height: '40',
    vertical: 'top-56',
    horizontal: 'right-10',
    widthLargeScreen: '80',
    heightLargeScreen: '80',
    verticalLargeScreen: 'top-36',
    horizontalLargeScreen: 'right-96',
    animationDelay: '1',
    color: 'fuchsia-500',
  },  
  {
    id: 1,
    width: '40',
    height: '40',
    vertical: 'top-80',
    horizontal: 'left-14',
    widthLargeScreen: '72',
    heightLargeScreen: '72',
    verticalLargeScreen: 'top-0',
    horizontalLargeScreen: 'left-96',
    animationDelay: '3',
    color: 'yellow-500',
  },
  {
    id: 2,
    width: '40',
    height: '40',
    vertical: 'top-0',
    horizontal: 'right-80',
    widthLargeScreen: '72',
    heightLargeScreen: '72',
    verticalLargeScreen: 'top-80',
    horizontalLargeScreen: 'left-96',
    animationDelay: '2',
    color: 'cyan-500',
  },
]