export const bgObjs = [
  {
    id: 0,
    width: '40',
    height: '40',
    vertical: 'top-56',
    horizontal: 'right-10',
    widthLg: '80',
    heightLg: '80',
    verticalLg: 'top-36',
    horizontalLg: 'right-96',
    animationDelay: '1',
    color: 'fuchsia-500',
  },  
  {
    id: 1,
    width: '40',
    height: '40',
    vertical: 'top-80',
    horizontal: 'left-14',
    widthLg: '72',
    heightLg: '72',
    verticalLg: 'top-0',
    horizontalLg: 'left-96',
    animationDelay: '3',
    color: 'yellow-500',
  },
  {
    id: 2,
    width: '40',
    height: '40',
    vertical: 'top-0',
    horizontal: 'right-80',
    widthLg: '72',
    heightLg: '72',
    verticalLg: 'top-80',
    horizontalLg: 'left-96',
    animationDelay: '2',
    color: 'cyan-500',
  },
]